### ISSUE TITLE
fongo 2.1.0 is not compatible with new java driver 3.6

### ISSUE THREAD

**Issue by zigzago** [fakemongo/fongo#316]
the stacktrace:

java.lang.NoSuchMethodError: com.mongodb.MongoDatabaseImpl.<init>(Ljava/lang/String;Lorg/bson/codecs/configuration/CodecRegistry;Lcom/mongodb/ReadPreference;Lcom/mongodb/WriteConcern;Lcom/mongodb/ReadConcern;Lcom/mongodb/operation/OperationExecutor;)V

	at com.mongodb.FongoMongoDatabase.<init>(FongoMongoDatabase.java:20)
	at com.mongodb.FongoMongoDatabase.<init>(FongoMongoDatabase.java:16)
	at com.mongodb.MockMongoClient.getDatabase(MockMongoClient.java:88)
	at com.github.fakemongo.Fongo.getDatabase(Fongo.java:110)

**Comment by rzanner** [comment]
...any updates on this?

**Comment by setry14** [comment]
Fongo people, whats up with this! Any fix yet?

**Comment by eonwhite** [comment]
I'm not a Fongo contributor and I don't know the inner workings of the MongoDB driver or Fongo at all, so I'm ill-suited for the task, but I use Fongo heavily in multiple projects, so I took a crack at trying to get things working with the 3.6 driver the other week.

I had a lot of challenges getting it to work due to a number of changes in the driver, apparently related to the new retryable-writes and the new session context, including some annoyances such as formerly public interfaces that had been made no longer public. I got stuck once I ran up against the MockMongoClient's use of Objenesis no longer working, and I've been slammed with other stuff, so I haven't had much time to look at it lately. If anyone else is interested in looking at it, I can put up what I've done so far though if it'd be helpful.

**Comment by jyothis85** [comment]
Thats a good idea. Please commit your changes to a new branch for mongo-driver-3.6 and others can continue from where you left.

**Comment by twillouer** [comment]
Hi, i'm working (very, very, very) slowly on it, but if anyone have a clean solution, it will be better

**Comment by vjrepo** [comment]
Any update please, we have a new requirement to make use change stream available in 3.6 and maintain our existing test cases too.

**Comment by rradillen** [comment]
Spring boot's release candidate for version 2.0.0 uses a 3.6.x version of the mongo driver. This problem will be encountered a lot more when it is released.

**Comment by twillouer** [comment]
can you test with driver36 branch (it's not finish yet)

**Comment by benjaminkomen** [comment]
Sorry to interrupt in this thread, but I have a similar issue since upgrading to the mongo driver 3.6.2. Some unit tests using fongo 2.1.0 give the following error:
java.lang.NullPointerException
	at com.mongodb.Mongo.createClientSession(Mongo.java:870)
	at com.mongodb.Mongo$3.getClientSession(Mongo.java:862)
	at com.mongodb.Mongo$3.execute(Mongo.java:819)
	at com.mongodb.Mongo$3.execute(Mongo.java:809)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:141)
	at com.mongodb.DBCursor.one(DBCursor.java:679)
	at com.mongodb.DBCollection.findOne(DBCollection.java:829)
	at com.mongodb.DBCollection.findOne(DBCollection.java:792)
	at com.mongodb.DBCollection.findOne(DBCollection.java:739)
	at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:515)
	at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:92)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:98)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:89)
	at com.mongodb.FongoDB.getCollection(FongoDB.java:84)
	at com.mongodb.FongoDB.getCollection(FongoDB.java:34)

Because this credentialsList for which the size was checked was null.

However, I tested with your driver36 branch and this seems to fix the issue! So please release it!

**Comment by twillouer** [comment]
Hi,

Can you try against the driver36 branch ?

**Comment by g051051** [comment]
I don't see any changes to the MockMongoClient class to address the credentialsList issue, so what do you expect to be different?

**Comment by benjaminkomen** [comment]
@g051051 I think you misinterpreted my comment. My issue with the NPE on the credentialsList is actually already resolved when I use the current driver36 branch. As I said in the last line of my previous comment.

**Comment by benjaminkomen** [comment]
I don't know.

**Comment by lecogiteur** [comment]
Hi,

Same problem with async driver

```
An exception or error caused a run to abort: com.mongodb.async.client.MongoDatabaseImpl.<init>(Ljava/lang/String;Lorg/bson/codecs/configuration/CodecRegistry;Lcom/mongodb/ReadPreference;Lcom/mongodb/WriteConcern;Lcom/mongodb/ReadConcern;Lcom/mongodb/operation/AsyncOperationExecutor;)V 
java.lang.NoSuchMethodError: com.mongodb.async.client.MongoDatabaseImpl.<init>(Ljava/lang/String;Lorg/bson/codecs/configuration/CodecRegistry;Lcom/mongodb/ReadPreference;Lcom/mongodb/WriteConcern;Lcom/mongodb/ReadConcern;Lcom/mongodb/operation/AsyncOperationExecutor;)V
```

**Comment by twillouer** [comment]
@lecogiteur I try to correct the async driver, can you take a try ?

**Comment by eivinhb** [comment]
I thought I'd drop in extra 👍

We have a couple of Spring Boot projects that need this fixed to be able to upgrade to Spring Boot 2. The fix branch driver36 works for us. But we had only trouble with the constructor of `MongoDatabaseImpl` in the driver using fongo 2.1.1.

**Comment by lecogiteur** [comment]
@twillouer On my side I have compiled the branch driver36 and the async driver works for me.

Thanks :+1:

**Comment by twillouer** [comment]
some unit tests are not working (I don't have a good return in some case).

If you absolutely need this version, I can release it, but... with consequences :-(

**Comment by Hades32** [comment]
@twillouer it would be super helpful to have a pre-release on maven central :+1:

**Comment by twillouer** [comment]
2.2.0-RC1 is out

**Comment by bsautel** [comment]
Thanks a lot @twillouer! I recently upgraded my project to Spring Boot 2 and I was blocked by this issue. With this 2.2.0-RC1 version, all my tests are passing!

**Comment by arongas** [comment]
Singed in just to say Thnx. 
I needed this fix! Works fine for me as well

**Comment by joschi** [comment]
@twillouer Fongo 2.2.0-RC1 works great with the MongoDB Java Driver 3.6.3 and MongoJack 2.8.1. 👍

**Comment by Hades32** [comment]
works fine here, too! Thank you for your continued efforts of this great project! Really no idea how I would develop without it :+1:

**Comment by eonwhite** [comment]
This is great news. I've just tried out 2.2.0-RC1 with 3.6.3 mongo-java-driver in two separate projects that both use Fongo, and all tests passed first try. Awesome work @twillouer, thank you.

**Comment by dmaksylewicz** [comment]
I'm confused, can someone confirm if either it is true or false that the 2.2.0-RC1 doesn't support the map-reduce? I've reported following issue but maybe I'm wrong:
https://github.com/fakemongo/fongo/issues/331

**Comment by BenRomberg** [comment]
@twillouer in case you're not already aware, `com.mongodb.DBCollection#findAndModify` doesn't seem to work if `remove` is set to `true`. We have some regressions in our test cases that seem to be related to the documents not being removed.

Let me know if you need more specific details or test cases!

**Comment by marekzebrowski** [comment]
for me 2.2.0-RC1 does not  work at all - `com.github.fakemongo.FongoException: Not implemented for command : { "update" : "users" , "ordered" : true}`

**Comment by camilla11** [comment]
I updated to 2.2.0-RC1 from 2.1.0 and am getting:

java.lang.NoClassDefFoundError: com/mongodb/OperationExecutor

	at com.github.fakemongo.Fongo.createMongo(Fongo.java:190)
	at com.github.fakemongo.Fongo.<init>(Fongo.java:103)
	at com.github.fakemongo.Fongo.<init>(Fongo.java:90)
	at com.github.fakemongo.Fongo.<init>(Fongo.java:82)

**Comment by albertotn** [comment]
I'm here for the same problem and switch to fongo 2.2.0-RC1 fixed problem.
My setup is mongo driver: 3.6.3 and I'm testing database/collection creation on my api and find over these collections

**Comment by niccottrell** [comment]
So, can we say this is fixed in 2.2.x?

**Comment by niccottrell** [comment]
@camilla11 Are you sure that fixed it? AFAIK OperationExecutor has been in com/mongodb/**operation** since at least version 3.2 of the drivers (see https://github.com/mongodb/mongo-java-driver/blob/3.2.x/driver-core/src/main/com/mongodb/operation/OperationExecutor.java)

**Comment by camilla11** [comment]
@niccottrell 
Pom.xml entry for the mongo driver:

```
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>3.6.3</version>
		</dependency>
```

And here is the fongo:

```
		<dependency>
			<groupId>com.github.fakemongo</groupId>
			<artifactId>fongo</artifactId>
			<version>2.2.0-RC1</version>
			<scope>test</scope>
		</dependency>
```

**Comment by persecond** [comment]
I am experiencing the same issue as @camilla11 however rather than the mongo-java-driver, I am using the mongodb-driver-core
```
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-core</artifactId>
            <version>3.6.3</version>
</dependency>
<dependency>
            <groupId>com.github.fakemongo</groupId>
            <artifactId>fongo</artifactId>
            <version>2.2.0-R1</version>
            <scope>test</scope>
</dependency>
```
This results in my application-context failing due to:
`Caused by: java.lang.ClassNotFoundException: com.mongodb.OperationExecutor`

**Comment by persecond** [comment]
I was able to get this to build and run without issue if I specified the "mongo-java-driver" as well as the "mongodb-driver-core". It seems the java driver is the key dependency.

**Comment by sgrillon14** [comment]
```
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongodb-driver-core</artifactId>
    <version>3.6.3</version>
</dependency>
<dependency>
    <groupId>com.github.fakemongo</groupId>
    <artifactId>fongo</artifactId>
    <version>2.2.0-R1</version>
    <scope>test</scope>
</dependency>
```

is OK but now, I have a Invalid date type on (`LocalDate`)  => error message is `Supported types are [org.joda.time.DateTime, org.joda.time.LocalDateTime, java.util.Date, java.lang.Long, long]`

**Comment by bwaldvogel** [comment]
You could give [mongo-java-server](https://github.com/bwaldvogel/mongo-java-server) a try.
I’ve successfully tested it with mongo-java-driver and mongodb-driver-async up to version 3.8.2.

It is similar to Fongo but implements the [wire protocol](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/). Thus, it is typically more resilient to refactorings in the mongo-java-driver.

However, please note that it is not a feature-complete implementation. Full-text search and map/reduce support, for example, are not yet implemented.

**Comment by thangarajks** [comment]
I had the same issue "java.lang.NoSuchMethodError: com.mongodb.MongoDatabaseImpl."
This has been fixed by using version "2.2.0-RC2"

**Comment by eugenejen** [comment]
@eonwhite : you removed the fongo from stardog just when I need to see what did you hack.

**Comment by eonwhite** [comment]
@eugenejen Sorry @eugenejen! I figured since at this point Fongo is compatible with the new driver, nobody needed it at this point. Hope you're well!

**Comment by eugenejen** [comment]
@eonwhite : unfortunately. fongo seems not working with 3.12.0 driver for sure. so i was wondering what did you do when 3.6 issue happened.

**Comment by JasonBeiJing** [comment]
bullshit

**Comment by eugenejen** [comment]
> bullshit

why?

**Comment by eugenejen** [comment]
I think what happened later in the specific close source project. fongo 2.1.1 and mongo-java-driver 3.12.1 could use the real database. We also had some morphia which also caused issues. Also we don't want to use 2.2.0-RC that fixed the issues for using in memory mode. Sorry I did not update the result and confuse you @JasonBeiJing. But we ended up remove the fongo due to it is not updated regularly. And we use docker container of mongod during tests. Since we don't want to be delayed due to fongo is not updated frequently as Mongo keeps releasing new drivers. We decide to remove fongo for good.

**Comment by niccottrell** [comment]
The Java driver is now up to version 4.0 and the server is 4.4. It's unlikely that Fongo will ever be able to simulate actual MongoDB results exactly so I would also recommend using a local mongod to write test data and then read it back. Setup functions can inject the test documents and you could use a different namespace per unit test to avoid pollution of test data
